name: Transform new JSON files

on:
  # 1) Se ejecuta en cualquier push que afecte la carpeta dialog_data
  push:
    paths:
      - 'dialog_data/**'
  # 2) Permite ejecutarlo manualmente desde la pestaña "Actions"
  workflow_dispatch:

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install  # si no tienes package.json con dependencias, omite

      - name: Run transform script
        run: node scripts/transform.js

      # (Opcional) Si quieres que los cambios de tu script se suban al repo:
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-transform dialog_data" || echo "No changes to commit"
          git push
