name: Transform new JSON files
permissions:
  contents: write

on:
  push:
    paths:
      - 'dialog_data/**'
  workflow_dispatch:

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run transform script
        run: node scripts/transform.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dialog_data_processed
          git commit -m "Auto-transform new JSON" || echo "No changes to commit"
          git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)
